name: charlesspencer
favicon: null
layout_spectrum: 0.9906239411793649
typography_spectrum: 0.8778276760131121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4189884904772043
  lightness: 0.3757293273229152
  saturation: 0.2957303780131042
  rhythmicContrast: 0.8508126877713948
purpose: []
