name: charlesspencer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff0'
    - '#525252'
    - '#b5f6aa'
    - '#8d8e86'
    - '#b0cc6d'
  brandStrength: 1
  lightness: 0.3757293273229152
  saturation: 0.4375
  rhythmicContrast: 0.8508126877713948
purpose: []
